# Initial mouse characteristics

At the start of each experiment with a mouse model, we record several measurements
or characteristics of each mouse. We record these measurements along with an identifier
for each mouse (for example, based on tags or ear notches), so that we can later 
link the initial characteristics of each mouse with later measurements on the same 
mouse. 

The values that we initially record for each mouse include: 

- `group`: An identifier for the experimental group to which the mouse
is assigned (e.g., "Control", "Group 1")
- `group_detail`: A longer description of the mouse's treatment group 
(e.g., "Vaccinated with vaccine candidate A at 4 and 8 weeks")
- `notch_id`: The ear notch pattern of the mouse (e.g., "0" for no notch, 
"1R" for one notch in the right ear)
- `mouse_number`: A number that corresponds with the mouse's ear notch patter; 
together with the mouse's group number, this provides
a unique identifier for each mouse in the experiment
- `cage_number`: The number of the cage to which the mouse is first assigned. 
This may change over the course of the experiment, as mice might be removed from 
a cage due to fighting, etc. Any of these later changes of cage will be 
recorded [where]
- `sex`: Whether the mouse is male ("m") or female ("f")
- `age`: Age 
- `strain`: The strain of the mouse (e.g., "C57BL/6J" for Black 6, "C3HeB/FeJ" for
Kramnik)

We have created a spreadsheet template that can be used to record these data,
which you can download by clicking [here](https://github.com/csu-impactb/CODING-TEAM-BOOKDOWN-/raw/main/DATA/mice_id_sheet.xlsx). This template currently includes
example data (colored in blue to help you remember that it's only there as an 
example). To Use this template, take a look at the example data, then delete it
and replace with the real data for your experiment.

Here is an example of how the first rows of this template might look once it's
filled out:

```{r}

```

This template should be used at the
initial time when mice are brought into the experiment. The file format is an
Excel file, so you can use it by saving it to your computer and then opening and
recording data with Excel. Later code in this chapter will read in a file in
this template format to provide basic summaries of the data. Later code will
read in these files to record the data in a project-wide database, which will
allow us to integrate it with other data collected over the course of the
experiment.

[Rules for naming the file. Include experiment name / study ID?]





